### ISSUE TITLE
Not really an issue but suggestion

### ISSUE THREAD

**Issue by js0505** [ctrlbold/dbatools#10]
Can I suggest adding the option to backup to multiple files for larger databases?  I have seen a 50 percent increase in performance on backups and restores.

**Comment by ctrlbold** [comment]
Great idea! I can also do runspaces which would make everything even faster. I'll add it to the todo list.

**Comment by js0505** [comment]
Awesome!  Quick question before diving into the detachattach script; does that also handle systems databases? 

    On Friday, February 26, 2016 7:32 AM, Chrissy LeMaire <notifications@github.com> wrote:
 

 Great idea! I can also do runspaces which would make everything even faster. I'll add it to the todo list.—

**Comment by ctrlbold** [comment]
It does not include master, msdb or model. I've found issues with master and msdb (though could add model easily). It seems doable and it's on my todo list, but had issues with the resource db. For my future reference, [this page](http://blogs.technet.com/b/beatrice/archive/2008/11/19/the-hidden-database-in-sql-server-2005-and-2008.aspx) will help.

**Comment by ctrlbold** [comment]
Hey @js0505, if you have any other suggestions, please come join the Trello board at https://trello.com/b/LcvGHeTF/dbatools

**Comment by js0505** [comment]
FYI, I can no longer view the DBATOOLS board on trello :( 

    On Saturday, April 30, 2016 9:08 PM, Chrissy LeMaire <notifications@github.com> wrote:
 

 Closed #10.—

**Comment by ctrlbold** [comment]
Oh! That's temporary. It'll be back within 48 hours at a new address, I'll
hit you up then.

**Comment by js0505** [comment]
Phew!  Had me scared there ;)
Thank you! 

    On Tuesday, May 3, 2016 7:24 AM, Chrissy LeMaire <notifications@github.com> wrote:
 

 Oh! That's temporary. It'll be back within 48 hours at a new address, I'll
hit you up then.

**Comment by ctrlbold** [comment]
I'm so happy that you're interested! What's your account on Trello? I'll
add you as a member when it's back.

**Comment by js0505** [comment]
js0505, I am also subscribed to Powershell and SQL Client Tools. 

    On Tuesday, May 3, 2016 7:33 AM, Chrissy LeMaire <notifications@github.com> wrote:
 

 I'm so happy that you're interested! What's your account on Trello? I'll
add you as a member when it's back.

**Comment by js0505** [comment]
...and Thank you! 

    On Tuesday, May 3, 2016 7:33 AM, Chrissy LeMaire <notifications@github.com> wrote:
 

 I'm so happy that you're interested! What's your account on Trello? I'll
add you as a member when it's back.

**Comment by ctrlbold** [comment]
k, please come back ;) https://trello.com/b/atkqo18g/

**Comment by js0505** [comment]
AWESOME!  Thank you!!! 

    On Tuesday, May 3, 2016 12:21 PM, Chrissy LeMaire <notifications@github.com> wrote:
 

 k, please come back ;) https://trello.com/b/atkqo18g/
