### ISSUE TITLE
Expand-SqlTlogResponsibly backups when -WhatIf is declared

### ISSUE THREAD

**Issue by MikeFal** [ctrlbold/dbatools#120]
If I run this command with the -WhatIf switch to validate what it's going to do, it backs up anyway. This could be problematic and generate uneeded backups, along with possibly disrupting the log backup chain. I suggest that this get altered that if -WhatIf is declared it will provide a message that a log backup will be taken, but not execute.

**Comment by ctrlbold** [comment]
added whatif support in two areas

**Comment by ctrlbold** [comment]
fixed
