### ISSUE TITLE
Using ReuseFolderStructure causes errors while migrating Database

### ISSUE THREAD

**Issue by dhrubomoy** [ctrlbold/dbatools#13]
### Specifications 
**Source:** Windows Server 2003
**SQL Server Version:** 2005

**Destination:** Windows Server 2008r2
**SQL Server Version:** 2008

**Command:** `Copy-SqlDatabase -Source SourceName -Destination DestinationName -Verbose -BackupRestore -ReuseFolderstructure -NetworkShare \\fileshare\sql\migration -All -Force`

### Expected behavior
Database migration should complete

### Actual Behavior
Shows whole bunch of errors. Like:

(1) `Join-AdminUnc : Cannot process argument transformation on parameter 'filepath'. Cannot convert value to type System.String.`
`At C:\dbatools\Function\Copy-SqlDatabase.ps1:650 char:45...`

(2) `WARNING: Restore failed: Restore failed for Server 'Destination'.`

(3) `Copy-SqlDatabase : Failed to update DatabaseOwnershipChaining for False on something on Destination`
`At C:\dbatools\Functions\Copy-SqlDatabase.ps1:1039 char:3...`

(4) `Copy-SqlDatabase : Failed to update Trustworthy to False for something on Destination`
`At C:\dbatools\Functions\Copy-SqlDatabase.ps1:1039 char:3...`

### Workaround
Not using _-ReuseFolderstructure_ seems to migrate database properly.

**Comment by ctrlbold** [comment]
Cannot repro even with same versions of sql (2005->2008). This may have been fixed inadvertently.

**Comment by potatoqualitee** [comment]
Please let us know if this has been fixed for sure in 0.9.127
