### ISSUE TITLE
Restore-HallengrenBackup error, not sure why

### ISSUE THREAD

**Issue by cusco** [ctrlbold/dbatools#18]
Hi.
First off, great work, thank you for this set of scripts. They look neat.

Now, I noticed that the detach/attach method does not attach again in the old server. And then I had permission troubles attaching again ( ?!?! ) 
So I was testing the restore from backup method, so I can maintain source server working with ease, if needed.

My backups are made using Ola's set of scripts. So I tested the restore-hallengrenBackup

My the error is:

```
File list could not be determined. This is likely due to connectivity issues or tiemouts with the SQL Server, the
database version is incorrect, or the SQL Server service account does not have access to the file share. Script
terminating.
At C:\Users\Administrator\Documents\WindowsPowerShell\Modules\dbatools\Functions\Restore-HallengrenBackups.ps1:206
char:12
+             catch { throw "File list could not be determined. This is likely due to conne ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (File list could...pt terminating.:String) [], RuntimeException
    + FullyQualifiedErrorId : File list could not be determined. This is likely due to connectivity issues or tiemouts
    with the SQL Server, the database version is incorrect, or the SQL Server service account does not have access to
   the file share. Script terminating.
```

**Could it be that -Path doesn't work as a NetworkPath?**
Maybe I need to copy the backups to this machine? If so, could you add -NetworkPath parameter?

**Comment by cusco** [comment]
And I just noticed that: "Path must be a valid UNC path (\\server\share) 

So I'm clueless as to the cause of the issue above

**Comment by ctrlbold** [comment]
Hey cusco,
What is the service account for the SQL Server? Is it a domain account? Does it have access to the path? Can you login as that service account and test? That's usually the issue.

**Comment by cusco** [comment]
Hi, thank you for your fast reply.

The share is public, anyone outside the domain can access it.
I'm using local administrator user (although it is in the domain as well)

How do I know the service user password to login as such?

**Comment by ctrlbold** [comment]
No problem. The share is public, but is it writable for public? It would have to allow anonymous if you are using a local computer account. That's not really supported right now :| But it's on my todo list. The service u/p would be given to you by your sysadmin. Perhaps you can try copying it to the server itself then doing the Path to local. The documentation is inaccurate -- local works, too, so long as it's in the proper format.

**Comment by cusco** [comment]
I set up the share as read only, should it be writable?
I can use a domain user later next time I test it.
I am the sysadmin, so i guess i can just reset the "Nt service\MSSQLSERVER" account's password .. but not sure I should.

got it for the local path.


Thank you

**Comment by ctrlbold** [comment]
Wait, oops. No need to write, it's the restore only script. 

Yeah, if it's not running as a domain account, unfortunately, that's not supported. Happy that local worked for you!

**Comment by ctrlbold** [comment]
No, don't reset your local service account. I was referring to "service account" being a domain account you ran to run the service, which you are not.
