### ISSUE TITLE
Restore-HallengrenBackups.ps1 - Test-SQLSA Function - Sysadmin check fails if User is a member of an AD Group with SysAdmin permissions

### ISSUE THREAD

**Issue by dougjjj** [ctrlbold/dbatools#2]
If the user running the script is a SysAdmin via an AD Group, the function will report they do not have permissions to run the restore process.

I'm looking into options to check User is a member any AD Groups with SysAdmin rights

**Comment by ctrlbold** [comment]
Hey Doug,
That darn function keeps popping up. It's old code that I thought I fixed (it's fixed in start-sqlservermigration and others). I'll update the code tomorrow. Thanks for the note!

**Comment by dougjjj** [comment]
Hey Chrissy,

Sounds great. Awesome work on the scripts, they are a lifesaver, I just
inherited a server with 1650 databases that I'm migrating to SQL 2014 and I
can't imagine doing it without them :)

Cheers

Doug

**Comment by ctrlbold** [comment]
Wow 1650! That would have been a crazy paid if done manually. I'm so happy you found the script useful.

I've updated the code for both issues. Thanks for the pull request. It was my first :D
