### ISSUE TITLE
sugestion: detatch/attach should re-attach files back on source server

### ISSUE THREAD

**Issue by cusco** [ctrlbold/dbatools#21]
Just because we migrate everything from one server to another, doesn't mean the source server should be left with no databases.
As such the scripts should leave the source server ready to run after migration.

**Comment by ctrlbold** [comment]
Hey Cusco,
You can use the -Reattach parameter to accomplish this in both Start-SqlMigration and Copy-SqlDatabase. Check out Get-Help Start-SqlMigration -Detailed for more info.

**Comment by ctrlbold** [comment]
Oh, also, come to the [dbatools Trello board](http://dbatools.io/trello). I'm accepting bugs/suggestions here, too, but I think you'll like that one better :)
