### ISSUE TITLE
Restore-HallengrenBackup doesn't work with Path character "$"

### ISSUE THREAD

**Issue by timw-be** [ctrlbold/dbatools#28]
Hi,

The Restore-HallengrenBackup function fails when trying to restore databases from a file share with character "$" in it's path.

When using Ola Hallengren's backup script to backup databases in an Availability Group, the backup files are stored in a folder with naming format "cluster_name$availability_group_name". The files are also named using naming format "cluster_name$availability_group_name_databasename_FULL_COPY_ONLY_20160627_213000.bak"

Basically, I receive the following error:
File list could not be determined. This is likely due to connectivity issues or tiemouts with the SQL Server, the database version is incorrect, or the SQL Server service account does not have access to the file share. Script terminating.

There's no issue with SQL server timeouts or service accounts access rights.

When I create a different folder (as a test) without a $ character in the same fileshare, copy a few database backups and remove the "$" in the copied backup files and point the Restore-HallengrenBackup function to this test folder on the fileshare restores work flawlessly.

Basically, the "$" character that Hallengren's backup script adds in the backup file path as a replacement of "\" breaks your restore script. Is there a way to mitigate this issue?

**Comment by ctrlbold** [comment]
Totally. I had this problem too with AGs and put it on the backburner because I had issues figuring it out. I have an idea about using  [Regex]::Escape() and will test it this weekend.

**Comment by ctrlbold** [comment]
Should be fixed :) Try now
