### ISSUE TITLE
copy-sqldatabase, no exclude parameter

### ISSUE THREAD

**Issue by jmccollum-bw** [ctrlbold/dbatools#29]
In the comments and help both show a exclude command to limit which DBs are copied. However when running the function the exclude command is not a valid parameter.

**Comment by ctrlbold** [comment]
Hey jmccollum-bw,
Thanks for filing a bug. I just tested this and it worked well

PS C:\> Copy-SqlDatabase -Source sql2016 -Destination sql2016a -DetachAttach -Reattach -Exclude db2 -AllDatabases
Attempting to connect to Sql Servers..
Checking access to remote directories...
Resolving NetBIOS name for SQL2016...
Resolving NetBIOS name for SQL2016A...

######### Database: db2 #########

Skipping db2

Database migration finished
Migration started: 06/30/2016 05:27:27
Migration completed: 06/30/2016 05:27:28
Total Elapsed time: 00:00:00

(db2 is the only db on that server). Can you paste your results along with Test-SqlConnection to your source server? You can remove any sensitive info.

**Comment by jmccollum-bw** [comment]
Thanks for responding so quickly!
I am using DBAtools version 0.8.1.8 from the PowerShell gallery.
PS C:\Users\jmccollum> Copy-SqlDatabase -Exclude "vra" -Source vrasql -Destination testsql
Copy-SqlDatabase : A parameter cannot be found that matches parameter name 'Exclude'.
At line:1 char:18
+ Copy-SqlDatabase -Exclude "vra" -Source vrasql -Destination testsql
+                  ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Copy-SqlDatabase], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Copy-SqlDatabase

Local PowerShell Enviornment


Windows    : 6.1.7601.65536
PowerShell : 5.0.10586.117
CLR        : 4.0.30319.42000
SMO        : 12.0.0.0
DomainUser : False
RunAsAdmin : False

SQL Server Connection Information

ServerName         : vrasql
BaseName           : vrasql
InstanceName       : (Default)
AuthType           : SQL Authentication
ConnectingAsUser   : sa
ConnectSuccess     : True
SqlServerVersion   : 12.0.4100
AddlConnectInfo    : N/A
RemoteServer       : True
IPAddress          :
NetBIOSname        : Unknown
RemotingAccessible : False
Pingable           : True
DefaultSQLPortOpen : True
RemotingPortOpen   : True


--
Jeff McCollum  |   Consultant  |   burwood group, inc.
jmccollum@burwood.com<mailto:jmccollum@burwood.com>   | Work: 309 621 7311  |   Fax: 312 327 4601

**Comment by ctrlbold** [comment]
The results of Test-SqlConnection do not reflect the same connection type as the Copy-SqlDatabase. With the first one, you're connecting using Windows credentials, and the second one, you passed the SQL Credential that contained sa. What you'll want to do is Copy-SqlDatabase -Source vrasql -Sql -SourceSqlCredential $yourcred then tab until Exclude appears. If it never does, it's not logging in properly.

**Comment by jmccollum-bw** [comment]
Sorry about that, I was just dropping off the credential in the sample I showed. So even when I specify the credential to be used, I am still getting the same result of 
A parameter cannot be found that matches parameter name 'exclude'
Looking at the code, in the parameters section, I don't see a parameter for -Exclude

**Comment by jmccollum-bw** [comment]
So uninstalling and re-installing the module fixed it. Thanks for the help!
