### ISSUE TITLE
Copy-SqlLinkedServer ignored Linked server 

### ISSUE THREAD

**Issue by msevorg** [ctrlbold/dbatools#4]
I ran Copy-SqlLinkedServer in both -WhatIf and not whatif mode and it ignored a linked server that was 2 characters long, "SQ".

Here is the script for creating the Linked Server for more information so you can try to diagnose what went wrong:

USE [master]
GO

/****** Object:  LinkedServer [SQ]    Script Date: 1/11/2016 3:23:27 PM ******/
EXEC master.dbo.sp_addlinkedserver @server = N'SQ', @srvproduct=N'Cache ODBC', @provider=N'MSDASQL.1', @datasrc=N'LABSQ'
 /* For security reasons the linked server remote logins password is changed with ######## */
EXEC master.dbo.sp_addlinkedsrvlogin @rmtsrvname=N'SQ',@useself=N'False',@locallogin=NULL,@rmtuser=NULL,@rmtpassword=NULL

GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'collation compatible', @optvalue=N'false'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'data access', @optvalue=N'true'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'dist', @optvalue=N'false'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'pub', @optvalue=N'false'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'rpc', @optvalue=N'false'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'rpc out', @optvalue=N'false'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'sub', @optvalue=N'false'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'connect timeout', @optvalue=N'0'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'collation name', @optvalue=null
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'lazy schema validation', @optvalue=N'true'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'query timeout', @optvalue=N'0'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'use remote collation', @optvalue=N'true'
GO

EXEC master.dbo.sp_serveroption @server=N'SQ', @optname=N'remote proc transaction promotion', @optvalue=N'false'
GO

**Comment by ctrlbold** [comment]
Thanks for the thorough info. I've added some additional information to the exception output, so please run it again. When I ran a test migration with the test linked server, I got The server option "lazy schema validation" is not available in this edition of SQL Server, but I did go from Ent to Std.
