### ISSUE TITLE
Detect server version before attempting CMS migration

### ISSUE THREAD

**Issue by ctrlbold** [ctrlbold/dbatools#7]
Central Management Server is only supported in SQL Server 2008 and above.

**Comment by js0505** [comment]
Don't you mean that CMS is only supported in SQL Server 2008 and Above not below. ;) 

    On Monday, February 22, 2016 7:24 AM, Chrissy LeMaire <notifications@github.com> wrote:
 

 Central Management Server is only supported in SQL Server 2008 and below.—

**Comment by ctrlbold** [comment]
Ha, yes, thank you.

**Comment by ctrlbold** [comment]
Fixed by pull request :)
