### ISSUE TITLE
Test-SqlTempDbConfiguration - tempdb on C: validation

### ISSUE THREAD

**Issue by ClaudioESSilva** [ctrlbold/dbatools#95]
This is not working as expected.
Was running a test on a server with only C drive and the test was false. Should be true.
After debug I saw that we are using:
($datafiles.rows | Where-Object { $_.FileName -like 'C:*' }).Rows.Count
but should be:
@($datafiles.rows | Where-Object { $_.FileName -like 'C:*' }).Count

@MikeFal want to make the correction? Or can I make it?

![test-sqltempdbconfiguration_bug](https://cloud.githubusercontent.com/assets/19521315/17311171/20c7807a-5841-11e6-9b15-c8e5a50ca032.PNG)

**Comment by MikeFal** [comment]
Go ahead and fix it, I'm swamped for doing anything until next week at the earliest.

Plus that makes total sense. :)

**Comment by ctrlbold** [comment]
@ClaudioESSilva that is a really old version you were looking at. Can you check on the latest, see if there's still an issue?

**Comment by MikeFal** [comment]
After discussion with @dansqldba and reviewing the new code, we identified a bug with the use of SQL queries when they return a single row. If this is the case, they are not in an array and don't have a .Count method. I've taken the newer code and updated with a fix for this. It's in #107 .
